from pathlib import Path

from app.core.config import (
    RAWDATA_DIR,
    ALL_INVOICES_DIR,
    DAILY_INVOICE_DIR,
    MONTHLY_INVOICE_DIR,
    MIXED_DOCUMENTS_DIR,
    UNKNOWN_DOCUMENTS_DIR,
    PROCESSED_DIR,
    PROCESSED_IMAGES_DIR,
    PROCESSED_TEXT_DIR,
    PROCESSED_METADATA_DIR,
    PROCESSED_OCR_JSON_DIR,
    PROCESSED_CHANDRA_JSON_DIR,
    PROCESSED_OPENAI_JSON_DIR,
    PROCESSED_SPATIAL_JSON_DIR,
    PROCESSED_CLASSIFICATION_JSON_DIR,
    PROCESSED_EXTRACTION_JSON_DIR,
    PROCESSED_SIGNATURE_JSON_DIR,
    PROCESSED_PIPELINE_JSON_DIR,
    PROCESSED_PREPROCESSED_IMAGES_DIR,
)


def create_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def create_required_directories() -> None:
    directories = [
        RAWDATA_DIR,
        ALL_INVOICES_DIR,
        DAILY_INVOICE_DIR,
        MONTHLY_INVOICE_DIR,
        MIXED_DOCUMENTS_DIR,
        UNKNOWN_DOCUMENTS_DIR,
        PROCESSED_DIR,
        PROCESSED_IMAGES_DIR,
        PROCESSED_TEXT_DIR,
        PROCESSED_METADATA_DIR,
        PROCESSED_PREPROCESSED_IMAGES_DIR,
        PROCESSED_OCR_JSON_DIR,
        PROCESSED_CHANDRA_JSON_DIR,
        PROCESSED_OPENAI_JSON_DIR,
        PROCESSED_SPATIAL_JSON_DIR,
        PROCESSED_CLASSIFICATION_JSON_DIR,
        PROCESSED_EXTRACTION_JSON_DIR,
        PROCESSED_SIGNATURE_JSON_DIR,
        PROCESSED_PIPELINE_JSON_DIR,
    ]

    for directory in directories:
        create_directory(directory)
